### ISSUE TITLE
[epic] Забрать ns в репо

### ISSUE THREAD

**Issue by vitkarpov** [yandex-ui/noscript-react#68]
- [x] оставить только нужные части (#70)
- [x] причесать кодстайл (#76)
- [x] избавиться от лишних зависимостей
   - [x] nommon (#71)
   - [x] vow (#73)
   - [x] jquery (#77)
- [x] ~~поднять поддержку браузеров, дропнуть старые полифилы~~ (пока не будем) (#72)

**Comment by vitkarpov** [comment]
Хочется сделать парочку несовместимых изменений в `ns`, поэтому думаю забрать его в репо вместе с тестами, удалить то, что не нужно и продолжать поддерживать здесь.

**Comment by Rebulus** [comment]
@vitkarpov может быть стоит форкнуть ns и развить его, как нечто, описанное в `noscript-react-demo`?

**Comment by Rebulus** [comment]
т.е. в само репо не вносить, а сделать из `noscript` штуку, которая поставляет всё, но любые элементы (в точисле и вью) могут быть подключаемыми?

**Comment by vitkarpov** [comment]
Да, можно и так. Мне просто кажется излишним разбивать это на два репо, потому что отдельно от реакта этот ноускрипт нельзя использовать.

**Comment by vitkarpov** [comment]
Можно будет всю разработку сосредоточить в одном репо: я очень сильно сомневаюсь, что сам по себе ноускрипт будет развиваться в текущем виде и здесь потребуются, скажем, какие-то фиксы оттуда — этого не будет

**Comment by Rebulus** [comment]
Почему же. Redux вполне жинеспособен без реакта. Кажется, и noscript может это делать. Пусть люди берут любую вьюху. Noscript будет только за флоу данных и стейт системы отвечать. Ммм?

**Comment by Rebulus** [comment]
@vitkarpov это твоя инициатива или будут помощники?

**Comment by vitkarpov** [comment]
Моя инициатива и только для нашего проекта. Поэтому не хочется раньше времени обобщать.

**Comment by vitkarpov** [comment]
Реакт хардкодиться не будет :) `ns` будет принимать его в параметры, так что если интерфейс совпадает, то можно заменить на любой виртуальный дом

**Comment by Rebulus** [comment]
Окей 😄

**Comment by vitkarpov** [comment]
Кое-как done :)
